# Generated by Django 3.0.8 on 2020-07-30 10:19

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_ctg', models.CharField(max_length=100)),
                ('food_ctg_image', imagekit.models.fields.ProcessedImageField(upload_to='food_ctg_photo')),
            ],
        ),
        migrations.CreateModel(
            name='FoodChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='일반', max_length=50)),
                ('food_ctgs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.FoodCategory')),
            ],
        ),
    ]
