# Generated by Django 2.1.15 on 2020-07-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_auto_20200702_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='food_kind',
            field=models.CharField(max_length=100),
        ),
    ]
